version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  api:
    build: ./app/api
    image: ghcr.io/mohammed0khater/shortify-devops-project/api:latest
    ports:
      - "5000:5000"
    environment:
      - DOMAIN=http://localhost:5000
    depends_on:
      - redis
  frontend:
    build: ./app/frontend
    image: ghcr.io/mohammed0khater/shortify-devops-project/frontend:latest
    ports:
      - "8080:80"
